
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-HomeController","number":27,"title":"Customize Home Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/27"},{"author":{"id":"MDQ6VXNlcjc3NjU4OTQ3","is_bot":false,"login":"AngelG261","name":""},"headRefName":"Angel-Tides","number":26,"title":"Tides service passes tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/26"},{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"Vinson-University","number":25,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/25"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-Location-Controller","number":24,"title":"Add Location Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/24"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-ZipCode","number":23,"title":"Implemented ZipCode Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/23"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-Location","number":21,"title":"Added Location Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/21"}]
