
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team01-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjU4OTQ3","is_bot":false,"login":"AngelG261","name":""},"headRefName":"Angel-Tides-Controller","number":29,"title":"Angel tides controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/29"},{"author":{"id":"MDQ6VXNlcjc3NjU4OTQ3","is_bot":false,"login":"AngelG261","name":""},"headRefName":"Angel-Tides","number":26,"title":"Tides service passes tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-5pm-1/pull/26"}]
